package VISTAS;

import CONTROLADORES.C_Inicio;
import Clases.ArbolBinario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class FormatoArbolBinario extends javax.swing.JFrame {
    private final ImageIcon error = new ImageIcon(getClass().getResource("/icon/error.png"));
    private final DefaultTableModel Table_model;
    private ArrayList<String[]> my_dict = new ArrayList<>();
    private final ArbolBinario ab = new ArbolBinario();
    private boolean inDefault=true;
    protected TableRowSorter<TableModel> rowSorter;
    
    public FormatoArbolBinario() {
        initComponents();
        setLocationRelativeTo(this);
        this.Panel_1.setBackground(new Color(0, 51, 51));
        Table_model = (DefaultTableModel)TBL_AREA.getModel();
        rowSorter = new TableRowSorter<>(TBL_AREA.getModel());
        TBL_AREA.setRowSorter(rowSorter);
        renderArbolBinario();
        renderTable(false, null);
        this.createSearcher();
    }
    
    public void createSearcher(){
        txtBuscar.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtBuscar.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtBuscar.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    private int getMedia(){
        String[][] data = Clases.data.getTablaHash().getNotNullData();
        int temp_media = 0;
        int media;
        for(String[] array: data){
            temp_media +=Integer.parseInt(array[0]);
        }
        temp_media /= data.length;
        media = buscarMedia(temp_media);
        return media;
    }
    
    /*   RECURSIVIDAD   */
    private int buscarMedia(int media_teorica){
        ArrayList<String[]> temp = Clases.data.getElements();
        if(temp.get(media_teorica)==null)
            media_teorica = this.buscarMedia(media_teorica+1);
        else
            media_teorica=Integer.parseInt(temp.get(media_teorica)[0]);
        return media_teorica;
    }
    
    private void reOrdenarTabla(int[] IDs){
        my_dict.clear();
        String[][] temp = Clases.data.getTablaHash().getNotNullData();
        for (int ID : IDs) {
            for (String[] temp1 : temp) {
                if (ID==Integer.parseInt(temp1[0])) {
                    my_dict.add(temp1);
                }
            }
        }
    }
    
    private void renderArbolBinario(){
        int count = 0;
        int media = this.getMedia();
        my_dict.clear();
        my_dict=Clases.data.getElements();
        Collections.shuffle(my_dict);
        while(my_dict.size()!=count){
            if(count==0){
                this.ab.insertar(media);
                System.out.println("El número más próximo a la media es: "+media);
            }
            else if(my_dict.get(count)!=null && Integer.parseInt(my_dict.get(count)[0])!=media){
                this.ab.insertar(Integer.parseInt(my_dict.get(count)[0]));
            }
            count++;
        }
    }

    public void renderTable(boolean whithMethod, int[] IDs){
        Table_model.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
        if(!whithMethod){
            my_dict = Clases.data.getElements();//TRAE LOS ELEMENTOS DE LA BASE DE DATOS
            inDefault=true;
        }else{
            reOrdenarTabla(IDs);
            inDefault=false;
        }
        my_dict = Clases.data.setFormatList(my_dict);//A LOS ELEMENTOS DE LA BASE DE DATOS LE DA AL CÓDIGO EL FORMATO
        for (String []Datos : my_dict){
            Table_model.addRow(Datos);//AGREGA LAS FILAS AL MODELO
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        Panel_1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDibujar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_AREA = new javax.swing.JTable();
        btnMostrar = new javax.swing.JToggleButton();
        CB_ARBOL = new javax.swing.JComboBox<>();
        btnVolver1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registros en Árbol Binario");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BÚSQUEDA POR ID:");

        btnDibujar.setBackground(new java.awt.Color(0, 102, 102));
        btnDibujar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDibujar.setForeground(new java.awt.Color(255, 255, 255));
        btnDibujar.setText("DIBUJAR");
        btnDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USAR MÉTODO:");

        TBL_AREA.setBackground(new java.awt.Color(204, 255, 255));
        TBL_AREA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código [ID]", "Descripción", "Prioridad", "Proveedor", "Costo", "Razón Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TBL_AREA);

        btnMostrar.setBackground(new java.awt.Color(0, 102, 102));
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        CB_ARBOL.setBackground(new java.awt.Color(0, 102, 102));
        CB_ARBOL.setForeground(new java.awt.Color(255, 255, 255));
        CB_ARBOL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Pre-Orden", "En-Orden", "Post-Orden" }));

        btnVolver1.setBackground(new java.awt.Color(0, 102, 102));
        btnVolver1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setText("VOLVER");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        txtBuscar.setBackground(new java.awt.Color(0, 102, 102));
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ÁRBOL BINARIO");

        separador.setBackground(new java.awt.Color(0, 153, 153));
        separador.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout Panel_1Layout = new javax.swing.GroupLayout(Panel_1);
        Panel_1.setLayout(Panel_1Layout);
        Panel_1Layout.setHorizontalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                            .addGap(325, 325, 325)
                            .addComponent(btnVolver1)
                            .addGap(18, 18, 18)
                            .addComponent(btnDibujar)
                            .addGap(296, 296, 296))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(Panel_1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_ARBOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_1Layout.setVerticalGroup(
            Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CB_ARBOL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        Inicio view = new Inicio();
        C_Inicio ctrl = new C_Inicio(view);
        ctrl.Iniciar();
        view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ABG vista = new ABG(ab);
        vista.setVisible(true);
    }//GEN-LAST:event_btnDibujarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        final int[] method;
        btnMostrar.setSelected(false);
        switch (CB_ARBOL.getSelectedIndex()) {
            case 0:
                if(!inDefault)
                    this.renderTable(false, null);
                else
                    JOptionPane.showMessageDialog(null, "Debes escoger un método de ordenamiento antes de continuar", "¡ADVERTENCIA!", HEIGHT, error);
                return;
            case 1:
                method = ab.getOrdenData(ab.getRaiz(), "preOrden");
                break;
            case 2:
                method = ab.getOrdenData(ab.getRaiz(), "inOrden");
                break;
            case 3:
                method = ab.getOrdenData(ab.getRaiz(), "postOrden");
                break;
            default:
                return;
        }
        this.renderTable(true, method);
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormatoArbolBinario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_ARBOL;
    private javax.swing.JPanel Panel_1;
    private javax.swing.JTable TBL_AREA;
    public javax.swing.JButton btnDibujar;
    private javax.swing.JToggleButton btnMostrar;
    public javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
